### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '~/OmniEvent_Model'

### ISSUE THREAD

**Issue by JingqiKang** [THU-KEG/OmniEvent#17]
![image](https://user-images.githubusercontent.com/88081081/189854103-6c1d67c0-0902-4a81-9c4f-3eb3dc8b6e79.png)

**Comment by JingqiKang** [comment]
Where to download /OmniEvent_Model?

**Comment by yaof20** [comment]
> Where to download /OmniEvent_Model?

Hi, this is an unexpected path error after we released OmniEvent on PyPi. We are trying to fix it and re-publish the package on PyPi.

A quick solution to this issue is that you can change `~/OmniEvent_Model` to `./OmniEvent_Model` in  [utils.py](https://github.com/THU-KEG/OmniEvent/blob/main/OmniEvent/utils.py) and rerun the example code. You may need to run ti code twice since you may encounter a network error at the first time. 

Let me know if it still doesn't work :)

**Comment by h-peng17** [comment]
Thanks for your issue report. We have fixed the bug in the lastest commit. (55dca605e5417ebcea83203b9faa065c0d366c4f)

**Comment by h-peng17** [comment]
You can use the code as suggested in `Easy Start`. And it will download the models needed automatically.

**Comment by JingqiKang** [comment]
sorry to bother you again. I encountered a new problem.
OSError: Unable to load weights from pytorch checkpoint file for 'xxx/.cache/OmniEvent_Model/s2s-mt5-eae/pytorch_model.bin' at 'xxx/.cache/OmniEvent_Model/s2s-mt5-eae/pytorch_model.bin'. If you tried to load a PyTorch model from a TF 2.0 checkpoint, please set from_tf=True.

**Comment by h-peng17** [comment]
You can try (1) delete cahced OmniEvent_Model (rm -r ~/.cache/OmniEvent_Model) (2) Re-download the checkpoint.

**Comment by h-peng17** [comment]
If the above suggestion doesn't work, can you provide your detailed environment info (especially the version of transformers)?

**Comment by JingqiKang** [comment]
Still having this problem
![image](https://user-images.githubusercontent.com/88081081/190183988-16227ddc-465e-4d59-a4e8-0196735845b5.png)

**Comment by yaof20** [comment]
> Still having this problem ![image](https://user-images.githubusercontent.com/88081081/190183988-16227ddc-465e-4d59-a4e8-0196735845b5.png)

You can try `pip install OmniEvent==0.1.5` and rerun the example codes.

Let me know if it still doesn't work :)

**Comment by JingqiKang** [comment]
It works. Many thanks!

**Comment by h-peng17** [comment]
Thanks for your issue report! :)
