### ISSUE TITLE
你好，请问下脚本中的ere在哪里下载？

### ISSUE THREAD

**Issue by huanghuidmml** [THU-KEG/OmniEvent#20]

**Comment by h-peng17** [comment]
你好，目前ere已经无法在LDC上找到。我们是之前下载的。

**Comment by huanghuidmml** [comment]
> 你好，目前ere已经无法在LDC上找到。我们是之前下载的。

你好，请问下这个数据集可以分享一份吗？万分感谢。我的邮箱：m13021933043@163.com

**Comment by h-peng17** [comment]
你好，由于ere的数据是受到LDC版权保护的，我们无法为你提供这个数据。你可以问问你们实验室或者学校有没有人参加过KBP比赛的，当时是有提供的。

**Comment by huanghuidmml** [comment]
> 你好，由于ere的数据是受到LDC版权保护的，我们无法为你提供这个数据。你可以问问你们实验室或者学校有没有人参加过KBP比赛的，当时是有提供的。

好的，谢谢了
