### ISSUE TITLE
您好，训练语料库(DuEE)需要多大的显存？

### ISSUE THREAD

**Issue by 1263180728** [THU-KEG/OmniEvent#21]

**Comment by h-peng17** [comment]
需要的CUDA显存跟模型大小和batch_size等有关系。你可以先训练base版本的模型，使用梯度累积的办法：把per_device_train_batch_size设低，将gradient_accumulation_steps设置的高一点。总的batch_size = per_device_train_batch_size * gradient_accumulation_steps。

**Comment by 1263180728** [comment]
您好，当训练到10%后，raceback加载完，出现错误：AttributeError: 'NoneType' object has no attribute 'batch_decode'
请问怎么解决。十分感谢！

**Comment by 1263180728** [comment]
trainer = Seq2SeqTrainer(
        args=training_args,
        model=model,
        tokenizer=tokenizer,
        train_dataset=train_dataset,
        eval_dataset=eval_dataset,
        compute_metrics=metric_fn,
        data_collator=train_dataset.collate_fn,
    )
