### ISSUE TITLE
您好，如何将自己训练好的参数加载到模型中，完成事件抽取任务？

### ISSUE THREAD

**Issue by 1263180728** [THU-KEG/OmniEvent#23]

**Comment by yaof20** [comment]
您好，

关于参数加载：
您可以选择checkpoint的路径，通过`from_pretrained`方法(如有)加载参数；或者参考pytorch的[load_state_dict](https://pytorch.org/docs/stable/generated/torch.nn.Module.html#torch.nn.Module.load_state_dict)等方法加载参数。

关于推理：
根据模型的`forward`的定义方式完成您所需要的任务。
