### ISSUE TITLE
base_processor.py的136行是否有bug呢？

### ISSUE THREAD

**Issue by roobustwalnut** [THU-KEG/OmniEvent#30]
发现一个小bug，/OmniEvent/OmniEvent/input_engineering/base_processor.py这个文件里的136行写的是：input_template: Optional[str][str]  = None,但是程序报错了，说Optional[str][str]的语法是错的。因此我改成了Optional[str]=None，就可以运行了。
不知道我这样改对不对呢？

**Comment by h-peng17** [comment]
小bug已经修复，谢谢指出（commit id: 54a5ec32c03f5a84a5d59c430ad3a389b743cde1）

**Comment by h-peng17** [comment]
结果评价模块可以评价目前支持的数据集，如ACE 2005, KBP, MAVEN等。你可以把完整的报错信息放一下吗

**Comment by roobustwalnut** [comment]
问题解决了，谢谢你们！不过还想问问golden trigger的原理大概是什么呢？在哪里可以查阅呀？

**Comment by h-peng17** [comment]
事件抽取一般分为两步：ED和EAE。ED先检测出事件，然后为检测出的事件抽取论元信息。golden trigger是指为正确标注的事件抽取论元信息，而不是为模型预测的（可能有噪声的）事件抽取论元信息。这种评测会直接评估EAE模型的性能，排除ED模型的影响。参考https://arxiv.org/abs/2202.12109
