### ISSUE TITLE
do_event_argument_extraction() missing 1 required positional argument: 'device'

### ISSUE THREAD

**Issue by Ashour1977** [THU-KEG/OmniEvent#34]
![Screenshot 2023-05-23 182408](https://github.com/THU-KEG/OmniEvent/assets/70287864/d60e8911-7525-46a0-8389-a535ce9837f2)

**Comment by Lyn4ever29** [comment]
> ![Screenshot 2023-05-23 182408](https://user-images.githubusercontent.com/70287864/240235947-d60e8911-7525-46a0-8389-a535ce9837f2.png)

It`s no problem.A little bug,you can fix it by youself.Add last argument:'device'

> ![Screenshot 2023-05-23 182408](https://user-images.githubusercontent.com/70287864/240235947-d60e8911-7525-46a0-8389-a535ce9837f2.png)

![image](https://github.com/THU-KEG/OmniEvent/assets/25952589/6d5379aa-7d4e-42e2-94fd-fd7928fc63e1)

**Comment by Yewx0310** [comment]
> ![Screenshot 2023-05-23 182408](https://user-images.githubusercontent.com/70287864/240235947-d60e8911-7525-46a0-8389-a535ce9837f2.png)

I would like to know which device you installed omnievent on,windows or linux ?

**Comment by Ashour1977** [comment]
> Yewx0310,
I am using windows OS, 
the issue is altready solved. 
thank you for your response

**Comment by Yewx0310** [comment]
This is an automatic reply, confirming that your e-mail was received. Thank you.--------------------------------------------Best WishesWenxue Ye.
