### ISSUE TITLE
There is a fatal bug ,please fix it .

### ISSUE THREAD

**Issue by Lyn4ever29** [THU-KEG/OmniEvent#35]
我用pip install OmniEvent安装的库，跑代码的时候发现一个bug,请修复它。bug位于OmniEvent/input_engineering/seq2seq_processor.py文件第52行，请及时处理。
![image](https://github.com/THU-KEG/OmniEvent/assets/25952589/8159f9ea-688c-4d42-9273-a5eda47de063)

**Comment by gal0is** [comment]
这应该是你自己代码文件的问题，代码库里没有这些乱码

**Comment by h-peng17** [comment]
这个是OmniEvet-0.1.5发布版本的问题，请安装最新的OmniEvent-0.1.6。注意如果使用的是非pypi的源的话，请先更新一下源。
