### ISSUE TITLE
运行EAE任务时出错

### ISSUE THREAD

**Issue by weiSENshu** [THU-KEG/OmniEvent#40]
运行时出现以下错误
![image](https://github.com/THU-KEG/OmniEvent/assets/62413717/5540d456-facf-4cfc-8a93-794715395644)

原因是OmniEvent/infer.py 文件的第134行 do_event_argument_extraction()函数少加了个参数‘device'

可以在seq2seq.py文件下找到对应函数
![image](https://github.com/THU-KEG/OmniEvent/assets/62413717/24cc067a-6211-462d-9273-cdce7898f521)
在添加'device'参数后，可以正常运行

**Comment by h-peng17** [comment]
好的，谢谢发现这个bug。我们已经在512e2fe76f966961d0e77bdb3c44e12b2ea42922中进行了修复。
