### ISSUE TITLE
Can you provide a maven-ere Omnievent pretrained model used for event relation extraction?

### ISSUE THREAD

**Issue by LinHanyueEsar** [THU-KEG/OmniEvent#44]
在您的OmniEvent 的 Demo中有一个完整的关于Event Extraction & Event Relation Extraction的样例，似乎是基于maven-ere训练出的？
请问我们是否可以获得这个模型？并用其进行infer任务？

**Comment by h-peng17** [comment]
Thanks for your attention! We will release the checkpoints soon!
谢谢你的关注，我们会在近期放出模型参数！
