### ISSUE TITLE
Constrained Decoding

### ISSUE THREAD

**Issue by JosephGatto** [THU-KEG/OmniEvent#46]
Is there example code on how to integrate Constrained Decoding for the Seq2Seq example model?

**Comment by h-peng17** [comment]
Thanks for the question. Currently, we didn't use constrained decoding in the Seq2Seq model, as we found the improvement of using constrained decoding is marginal (or even worse). Inheriting constrained decoding into our method requires implementing a Seq2Seq Trainer of your own, see [text2event](https://github.com/luyaojie/Text2Event/tree/main/seq2seq).
