### ISSUE TITLE
服务器连接不上huggingface，无法加载model，请教有没有什么更好的解决方案，谢谢！

### ISSUE THREAD

**Issue by WSKNOO** [THU-KEG/OmniEvent#49]
![image](https://github.com/THU-KEG/OmniEvent/assets/46177410/60a5fe5c-1e1e-47d1-b254-2ea50f2d5b79)

**Comment by h-peng17** [comment]
你可以到Huggingface transformers的model card文件手动将需要的文件一个一个下载下来。比如BERT：https://huggingface.co/bert-base-uncased/tree/main，你可以右键每个文件获得链接地址然后在服务器wget下载。当然，最好的解决方案是给服务器配置一个代理。

**Comment by WSKNOO** [comment]
谢谢您的解答！
