### ISSUE TITLE
Event Ontology 

### ISSUE THREAD

**Issue by nurakib** [THU-KEG/OmniEvent#52]
Hi,
I have been using this library for a project. I am using it for event detection, but I have not found the exact event ontology used to train the model. 

Does this ontology comprise event types from both ACE and MAVEN? Or is there any custom event ontology for the Event Detection model? Where can I access the ontology file? 

Thank you.

**Comment by h-peng17** [comment]
The ontology file will be stored in `./data/processed/<dataset_name>` after data processing.
