### ISSUE TITLE
找不到train

### ISSUE THREAD

**Issue by jqianaaaa** [THU-KEG/OmniEvent#55]
您好我按照您的说明文档进行模型训练的时候，当我进行到如图片所示的这一步时，我发现您的代码里没有train.sh该文件，请问这样该如何进行模型训练呢
![1709622557287](https://github.com/THU-KEG/OmniEvent/assets/156065335/b55d96e1-3a28-4067-89de-3c5e27ca33cd)

**Comment by h-peng17** [comment]
https://github.com/THU-KEG/OmniEvent/blob/main/examples/ED/run.sh 请参考这里的训练脚本
