### ISSUE TITLE
ValueError: 's2s-mt5-ed' is not a valid model identifier

### ISSUE THREAD

**Issue by Kangdi123** [THU-KEG/OmniEvent#60]
Hello, the following error occurs when running the code for ED tasks, missing model
ValueError: 's2s-mt5-ed' is not a valid model identifier

**Comment by wuyong97** [comment]
从清华大学网盘下载训练好的mt5模型失败，访问不了。
不知道作者能不能处理一下这个问题。或者把训练后的模型上传到其他可以访问下载的地方。

**Comment by h-peng17** [comment]
The cloud link is expired. I will update the link this month (Oct 2024).

**Comment by YiQing-Songs** [comment]
您好可以更新吗


> 云链接已过期。我将在本月（2024 年 10 月）更新链接。

**Comment by h-peng17** [comment]
Solved in #61
