### ISSUE TITLE
Link does not exist.

### ISSUE THREAD

**Issue by liuzeyu6** [THU-KEG/OmniEvent#61]
Hi, thank you for your outstanding work! 
The link provided in the Pipeline Evaluation module of the readme is working: https://cloud.tsinghua.edu.cn/f/799c8c7c44d24c1db2b7/?dl=1. Could you share another one?

**Comment by h-peng17** [comment]
s2s-mt5-eae: https://cloud.tsinghua.edu.cn/f/11172c738dd94a48a706/?dl=1
s2s-mt5-ed: https://cloud.tsinghua.edu.cn/f/46a3c30c2bb041d89b9f/?dl=1

**Comment by liuzeyu6** [comment]
Thank you!

**Comment by h-peng17** [comment]
As an urgent candidate, perhaps you can try this model (https://huggingface.co/THU-KEG/ADELIE-DPO-1.5B). It's more general and powerful for information extraction, and its scale is similar to the previous one. I will recheck the issues with the old version of the model soon.
